airbnb/accounts/urls.py
from django.urls import path
from django.contrib import admin

admin.autodiscover()

app_name = 'accounts'

from . views import (
  RegisterForm, EditUserProfileView,UserHouseLists
  
)

urlpatterns = [

    # path('create/', ProfileForm.as_view(), name='create'),
    path('edit/<username>', EditUserProfileView.as_view(), name='update'),
    path('user_lists/<username>/' , UserHouseLists.as_view(), name='user_lists'),

    
    
    
   
    
    
]

airbnb/house/urls.py
from django.urls import path
from django.contrib import admin

admin.autodiscover()

from . views import (
  HouseCreate, HouseList, HouseDetail, MyHouseList, 
  HouseUpdateView, HouseDeleteView, BookingView, SearchView
)

app_name = 'house'

urlpatterns = [
    path('create/', HouseCreate.as_view(), name='create'),
    path('' , HouseList.as_view(), name='list'),
    path('my_lists/' , MyHouseList.as_view(), name='my_lists'),
    path('<slug:slug>/', HouseDetail.as_view(), name='detail'),
    path('edit/<slug:slug>', HouseUpdateView.as_view(), name='update_house'),
    path('delete/<slug:slug>', HouseDeleteView.as_view(), name='delete_house'),
    path('book/', BookingView.as_view(), name='book'),

]

airbnb/templates/houses/delete_view.html
{% extends "base.html" %}

{% block content %}
<!--  header end -->	
            <!-- wrapper -->

        
            <div class="user-profile-menu-wrap fl-wrap">	
                    <div id="wrapper">
                        <!--content -->  
                        <div class="content">
                            <!--section --> 
                            <section id="sec1">
                                <!-- container -->
                                <div class="container">
                                    <!-- profile-edit-wrap -->
                           
                                            {% include "dash.html" %}
                                                        
                                                        <!-- user-profile-menu end-->                               
                                        
                                         
                                            
        
                                            <div class="col-md-9">
                                 
                                                    <form method="post">{% csrf_token %}
                                                            <p class="lead">Are you sure you want to delete "{{ object }}"?</p>
                                                            
                                                            <button value="submit" <a href="{% url 'logout' %}"class="log-out-btn">Confirm </button>
                                                        </form>
                                            </div>
                                        </div>
                                    </div>
                                    <!--profile-edit-wrap end -->
                                </div>
                                <!--container end -->
                            </section>
                            <!-- section end -->
                            <div class="limit-box fl-wrap"></div>
                      
                            <!-- section end -->
                        </div>
                    </div>
{% endblock content %}

airbnb/templates/houses/list_houses.html
{% extends "base.html" %}

{% block content %}

   <!--  header end -->
            <!-- wrapper -->
            <div id="wrapper">
                <!--  content  -->
                <div class="content">
                    <!--  section  -->
                    <section class="parallax-section" data-scrollax-parent="true">
                        <div class="bg par-elem "  data-bg="images/bg/3.jpg" data-scrollax="properties: { translateY: '30%' }"></div>
                        <div class="overlay"></div>
                        <div class="container">
                            <div class="section-title center-align">
                                <h2><span>Listings Without Map</span></h2>
                                <div class="breadcrumbs fl-wrap"><a href="#">Home</a><a href="#">Listings</a><span>Listings Without Map</span></div>
                                <span class="section-separator"></span>
                            </div>
                        </div>
                        <div class="header-sec-link">
                            <div class="container"><a href="#sec1" class="custom-scroll-link">Let's Start</a></div>
                        </div>
                    </section>
                    <!--  section  end-->
                    <!--  section  -->
                    <section class="gray-bg no-pading no-top-padding" id="sec1">
                        <div class="col-list-wrap  center-col-list-wrap left-list">
                            <div class="container">
                                <div class="listsearch-maiwrap box-inside fl-wrap">
                                    <div class="listsearch-header fl-wrap">
                                        <h3>Results For : <span>All Listings</span></h3>
                                        <div class="listing-view-layout">
                                            <ul>
                                                <li><a class="grid active" href="#"><i class="fa fa-th-large"></i></a></li>
                                                <li><a class="list" href="#"><i class="fa fa-list-ul"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <!-- listsearch-input-wrap  -->
                                    <div class="listsearch-input-wrap fl-wrap">
                                        <div class="listsearch-input-item">
                                            <i class="mbri-key single-i"></i>
                                            <input type="text" placeholder="Keywords?" value=""/>
                                        </div>
                                        <div class="listsearch-input-item">
                                            <select data-placeholder="Location" class="chosen-select" >
                                                <option>All Locations</option>
                                                <option>Bronx</option>
                                                <option>Brooklyn</option>
                                                <option>Manhattan</option>
                                                <option>Queens</option>
                                                <option>Staten Island</option>
                                            </select>
                                        </div>
                                        <div class="listsearch-input-item">
                                            <select data-placeholder="All Categories" class="chosen-select" >
                                                <option>All Categories</option>
                                                <option>Shops</option>
                                                <option>Hotels</option>
                                                <option>Restaurants</option>
                                                <option>Fitness</option>
                                                <option>Events</option>
                                            </select>
                                        </div>
										<div class="listsearch-input-text" id="autocomplete-container">
											<label><i class="mbri-map-pin"></i> Enter Addres </label>
											<input type="text" placeholder="Destination , Area , Street" id="autocomplete-input" class="qodef-archive-places-search" value=""/>
											<a  href="#"  class="loc-act qodef-archive-current-location"><i class="fa fa-dot-circle-o"></i></a>
										</div>
                                        <!-- hidden-listing-filter -->
                                        <div class="hidden-listing-filter fl-wrap">
                                            <div class="distance-input fl-wrap">
                                                <div class="distance-title"> Radius around selected destination <span></span> km</div>
                                                <div class="distance-radius-wrap fl-wrap">
                                                    <input class="distance-radius rangeslider--horizontal" type="range" min="1" max="100" step="1" value="1" data-title="Radius around selected destination">
                                                </div>
                                            </div>
                                            <!-- Checkboxes -->
                                            <div class=" fl-wrap filter-tags">
                                                <h4>Filter by Tags</h4>
                                                <div class="filter-tags-wrap">
                                                    <input id="check-a" type="checkbox" name="check" checked>
                                                    <label for="check-a">Elevator in building</label>
                                                </div>
                                                <div class="filter-tags-wrap">
                                                    <input id="check-b" type="checkbox" name="check">
                                                    <label for="check-b">Friendly workspace</label>
                                                </div>
                                                <div class="filter-tags-wrap">
                                                    <input id="check-c" type="checkbox" name="check">
                                                    <label for="check-c">Instant Book</label>
                                                </div>
                                                <div class="filter-tags-wrap">
                                                    <input id="check-d" type="checkbox" name="check">
                                                    <label for="check-d">Wireless Internet</label>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- hidden-listing-filter end -->
                                        <button class="button fs-map-btn">Update</button>
                                        <div class="more-filter-option">More Filters <span></span></div>
                                    </div>
                                    <!-- listsearch-input-wrap end -->
                                </div>
                                <!-- list-main-wrap-->
                                <div class="list-main-wrap fl-wrap card-listing">
                                    <!-- listing-item -->
                                    {% for house in object_list %}
                                    <div class="listing-item">
                                        <article class="geodir-category-listing fl-wrap">
                                            <div class="geodir-category-img">
                                              {% if house.images %}
                                                <img src="{{house.images.url}}" alt="">
                                                {%endif%}
                                                <div class="overlay"></div>
                                                <div class="list-post-counter"><span>4</span><i class="fa fa-heart"></i></div>
                                            </div>
                                            <div class="geodir-category-content fl-wrap">
                                                <a class="listing-geodir-category" href="listing.html">{{house.house_type}}</a>
                                                <div class="listing-avatar"><a href="{%url 'accounts:user_lists' house.owner.username%}"><img src="{{house.owner.profile.avatar.url}}"></a>
                                                    <span class="avatar-tooltip">Added By  <strong>{{house.owner.username}}</strong></span>
                                                </div>
<h3><a href="{% url 'house:detail' house.slug %}">{{house.adtitle}}</a></h3>
                                                <p>{{house.description|truncatechars:100}}</p>
                                                <div class="geodir-category-options fl-wrap">
                                                    <div class="listing-rating card-popup-rainingvis" data-starrating2="5">
                                                        <span>(7 reviews)</span>
                                                    </div>
                                                    <div class="geodir-category-location"><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i> {{house.location}}</a></div>
                                                </div>
                                            </div>
                                        </article>
                                    </div>
                                    <!-- listing-item end-->
                                    {%endfor%}
                                    
                                    <!-- pagination-->
                                    <div class="pagination">
                                        <a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
                                        <a href="#" class="blog-page transition">1</a>
                                        <a href="#" class="blog-page current-page transition">2</a>
                                        <a href="#" class="blog-page transition">3</a>
                                        <a href="#" class="blog-page transition">4</a>
                                        <a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
                                    </div>
                                </div>
                                <!-- list-main-wrap end-->
  
      
{%endblock content%}

airbnb/templates/houses/my_listings.html
{% extends "base.html" %}

{% block content %}
            <!--  header end -->	
            <!-- wrapper -->

        
                <div class="user-profile-menu-wrap fl-wrap">	
            <div id="wrapper">
                <!--content -->  
                <div class="content">
                    <!--section --> 
                    <section id="sec1">
                        <!-- container -->
                        <div class="container">
                            <!-- profile-edit-wrap -->
                   
                                    {% include "dash.html" %}
                                                
                                                <!-- user-profile-menu end-->                               
                                
                                 
                                    

                                    <div class="col-md-9">
                                        <div class="dashboard-list-box fl-wrap">
                                            <div class="dashboard-header fl-wrap">
                                                <h3>Indox</h3>
                                            </div>
                                             
                                            {% for object in object_list%}
                                            <div class="dashboard-list">
                                                <div class="dashboard-message">
                                                    <div class="dashboard-listing-table-image">
                                                        <a href="listing-single.html"><img src="{{object.images.url}}" alt=""></a>
                                                    </div>
                                                    <div class="dashboard-listing-table-text">
                                                        <h4><a href="{% url 'house:detail' object.slug %}">{{object.adtitle}}</a></h4>
                                                        <span class="dashboard-listing-table-address"><i class="fa fa-map-marker"></i><a  href="#">{{object.location}}</a></span>
                                                        <div class="listing-rating card-popup-rainingvis fl-wrap" data-starrating2="3">
                                                            <span>(2 reviews)</span>
                                                        </div>
                                                        <ul class="dashboard-listing-table-opt  fl-wrap">
                                                            <li><a href="{%url 'house:update_house' object.slug%} ">Edit <i class="fa fa-pencil-square-o"></i></a></li>
                                                            <li><a href="{% url 'house:delete_house' object.slug %}" class="del-btn">Delete <i class="fa fa-trash-o"></i></a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- dashboard-list end-->                             {%endfor%}     
                                            
                                                </div>
                                      
                                            <!-- dashboard-list end-->   
                                       
                                        <!-- pagination-->
                                        <div class="pagination">
                                            <a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
                                            <a href="#">1</a>
                                            <a href="#" class="current-page">2</a>
                                            <a href="#">3</a>
                                            <a href="#">4</a>
                                            <a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--profile-edit-wrap end -->
                        </div>
                        <!--container end -->
                    </section>
                    <!-- section end -->
                    <div class="limit-box fl-wrap"></div>
              
                    <!-- section end -->
                </div>
            </div>
  {% endblock content%}

airbnb/templates/houses/user_listings.html
{% extends "base.html" %}

{% block content %}
             <!--  header end -->
            <!-- wrapper -->
            <div id="wrapper">
                <!--Content -->
                <div class="content">
                    <!--section -->
                    <section class="parallax-section small-par color-bg">
                        <div class="shapes-bg-big"></div>
                        <div class="container">
                            <div class="section-title center-align">
                                <div class="breadcrumbs fl-wrap"><a href="#">Home</a><a href="#">Listing</a><span>User profile</span></div>
                                <h2><span>User : {{request.user.username}}</span></h2>
                                <div class="user-profile-avatar"><img src="{{request.user.profile.avatar.url}}" alt=""></div>
                                <div class="user-profile-rating clearfix">
                                    <div class="listing-rating card-popup-rainingvis" data-starrating2="5">
                                        <span>(37 reviews)</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="header-sec-link">
                            <div class="container"><a href="#sec1" class="custom-scroll-link">About user</a></div>
                            
                        </div>
                    </section>
                    <!-- section end -->
                    <!--section -->
                    <section class="gray-bg" id="sec1">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="list-single-main-item fl-wrap">
                                        <div class="list-single-main-item-title fl-wrap">
                                            <h3>About <span>{{request.user.username}}</span></h3>
                                        </div>
                                        <p>{{request.user.profile.bio}}</p>
                                        <a href="#" class="btn transparent-btn float-btn">Visit Website <i class="fa fa-angle-right"></i></a>
                                    </div>
                                    <div class="listsearch-header fl-wrap">
                                        <h3>{{request.user.username}} Listings</h3>
                                        <div class="listing-view-layout">
                                            <ul>
                                                <li><a class="grid active" href="#"><i class="fa fa-th-large"></i></a></li>
                                                <li><a class="list" href="#"><i class="fa fa-list-ul"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    
                                    <!-- list-main-wrap-->
                                    <div class="list-main-wrap fl-wrap card-listing ">
                                            {% for object in object_list %}
                                        <!-- listing-item -->
                                        <div class="listing-item">
                                            <article class="geodir-category-listing fl-wrap">
                                                <div class="geodir-category-img">
                                                    <img src="{{object.images.url}}" alt="">
                                                    <div class="overlay"></div>
                                                    <div class="list-post-counter"><span>4</span><i class="fa fa-heart"></i></div>
                                                </div>
                                                <div class="geodir-category-content fl-wrap">
                                                    <a class="listing-geodir-category" href="listing.html">{{object.house_type}}</a>
                                                    <div class="listing-avatar"><a href="author-single.html"><img src="{{object.owner.profile.avatar}}" alt=""></a>
                                                        <span class="avatar-tooltip">Added By  <strong>{{object.owner.username}}</strong></span>
                                                    </div>
                                                    <h3><a href="{% url 'house:detail' object.slug %}">{{object.adtitle}}</a></h3>
                                                    <p>{{object.description|truncatechars:100}}.</p>
                                                    <div class="geodir-category-options fl-wrap">
                                                        <div class="listing-rating card-popup-rainingvis" data-starrating2="5">
                                                            <span>(7 reviews)</span>
                                                        </div>
                                                        <div class="geodir-category-location"><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i> </a>{{object.location}}</div>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                        <!-- listing-item end-->
                                        {%endfor%}
                                       
                                        
                                   
                                        <div class="clearfix"></div>
                                       
                                    
                                      
                                        <!-- pagination-->
                                        <div class="pagination">
                                            <a href="#" class="prevposts-link"><i class="fa fa-caret-left"></i></a>
                                            <a href="#" class="current-page">1</a>
                                            <a href="#">2</a>
                                            <a href="#">3</a>
                                            <a href="#" class="nextposts-link"><i class="fa fa-caret-right"></i></a>
                                        </div>
                                    </div>
                                    <!-- list-main-wrap end-->
                                </div>
                                <!--box-widget-wrap -->
                                <div class="col-md-4">
                                    <div class="fl-wrap">
                                        <!--box-widget-item -->
                                        <div class="box-widget-item fl-wrap">
                                            <div class="box-widget-item-header">
                                                <h3>User Contacts : </h3>
                                            </div>
                                            <div class="box-widget">
                                                <div class="box-widget-content">
                                                    <div class="list-author-widget-contacts list-item-widget-contacts">
                                                        <ul>
                                                            <li><span><i class="fa fa-map-marker"></i> Adress :</span> <a href="#">{{request.user.profile.adress}}</a></li>
                                                            <li><span><i class="fa fa-phone"></i> Phone :</span> <a href="#">{{request.user.profile.phone}}</a></li>
                                                            <li><span><i class="fa fa-envelope-o"></i> Mail :</span> <a href="#">{{request.user.email}}</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="list-widget-social">
                                                        <ul>
                                                            <li><a href="{{request.user.profile.facbook}}" target="_blank" ><i class="fa fa-facebook"></i></a></li>
                                                            <li><a href="{{request.user.profile.twitter}}" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                                            <li><a href="{{request.user.profile.phone}}" target="_blank" ><i class="fa fa-whatsapp"></i></a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--box-widget-item end -->
                                        <!--box-widget-item -->
                                        <div class="box-widget-item fl-wrap">
                                            <div class="box-widget-item-header">
                                                <h3>Get in Touch : </h3>
                                            </div>
                                            <div class="box-widget">
                                                <div class="box-widget-content">
                                                    <form id="add-comment" class="add-comment custom-form">
                                                        <fieldset>
                                                            <label><i class="fa fa-user-o"></i></label>
                                                            <input type="text" placeholder="Your Name *" value=""/>
                                                            <div class="clearfix"></div>
                                                            <label><i class="fa fa-envelope-o"></i>  </label>
                                                            <input type="text" placeholder="Email Address*" value=""/>
                                                            <textarea cols="40" rows="3" placeholder="Your message:"></textarea>
                                                        </fieldset>
                                                        <button class="btn  big-btn  color-bg flat-btn">Send Message<i class="fa fa-angle-right"></i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                        <!--box-widget-item end -->
                                    </div>
                                </div>
                                <!--box-widget-wrap end-->
                            </div>
                        </div>
                    </section>
               
                {% endblock content%}
    