airbnb/accounts/urls.py
from django.urls import path
from django.contrib import admin

admin.autodiscover()

app_name = 'accounts'

from . views import (
  RegisterForm, EditUserProfileView,UserHouseLists
  
)

urlpatterns = [

    # path('create/', ProfileForm.as_view(), name='create'),
    path('edit/<username>', EditUserProfileView.as_view(), name='update'),
    path('user_lists/<username>/' , UserHouseLists.as_view(), name='user_lists'),

    
    
    
   
    
    
]

airbnb/house/urls.py
from django.urls import path
from django.contrib import admin

admin.autodiscover()

from . views import (
  HouseCreate, HouseList, HouseDetail, MyHouseList, 
  HouseUpdateView, HouseDeleteView, BookingView, SearchView
)

app_name = 'house'

urlpatterns = [
    path('create/', HouseCreate.as_view(), name='create'),
    path('' , HouseList.as_view(), name='list'),
    path('my_lists/' , MyHouseList.as_view(), name='my_lists'),
    path('<slug:slug>/', HouseDetail.as_view(), name='detail'),
    path('edit/<slug:slug>', HouseUpdateView.as_view(), name='update_house'),
    path('delete/<slug:slug>', HouseDeleteView.as_view(), name='delete_house'),
    path('book/', BookingView.as_view(), name='book'),

]

airbnb/templates/coming-soon.html
<!DOCTYPE HTML>
<html lang="en">
    
<!-- Mirrored from citybook.kwst.net/coming-soon.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 Jun 2018 10:15:44 GMT -->
<head>
        <!--=============== basic  ===============-->
        <meta charset="UTF-8">
        <title>Citybook -Directory Listing Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="robots" content="index, follow"/>
        <meta name="keywords" content=""/>
        <meta name="description" content=""/>
        <!--=============== css  ===============-->
        <link type="text/css" rel="stylesheet" href="css/reset.css">
        <link type="text/css" rel="stylesheet" href="css/plugins.css">
        <link type="text/css" rel="stylesheet" href="css/style.css">
        <link type="text/css" rel="stylesheet" href="css/color.css">
        <!--=============== favicons ===============-->
        <link rel="shortcut icon" href="images/favicon.ico">
    </head>
    <body>
        <!-- loader-->
        <div class="loader-wrap">
            <div class="pin"></div>
            <div class="pulse"></div>
        </div>
        <!--loader end -->
        <!--Main-->
        <div id="main">
            <!--wrapper -->
            <div class="fixed-bg">
                <div class="bg"  data-bg="images/bg/27.jpg"></div>
                <div class="overlay"></div>
                <div class="bubble-bg"></div>
            </div>
            <!-- cs-wrapper -->
            <div class="cs-wrapper fl-wrap">
                <!-- container  -->
                <div class="container small-container counter-widget" data-countDate="09/12/2019">
                    <div class="cs-logo"><img src="images/logo.png" alt=""></div>
                    <span class="section-separator"></span>
                    <h3 class="soon-title">Our website is coming soon!</h3>
                    <!-- countdown -->
                    <div class="countdown fl-wrap">
                        <div class="cs-countdown-item">
                            <span class="days rot">00</span>
                            <p>days</p>
                        </div>
                        <div class="cs-countdown-item">
                            <span class="hours rot">00</span>
                            <p>hours </p>
                        </div>
                        <div class="cs-countdown-item no-dec">
                            <span class="minutes rot2">00</span>
                            <p>minutes </p>
                        </div>
                        <div class="cs-countdown-item">
                            <span class="seconds rot2">00</span>
                            <p>seconds</p>
                        </div>
                    </div>
                    <!-- countdown end -->
                    <div class="subcribe-form fl-wrap">
                        <p>Sign up now to our newsletter and you will be one of the first know
                            when our   new website as ready
                        </p>
                        <form id="subscribe">
                            <input class="enteremail" name="email" id="subscribe-email" placeholder="Email" spellcheck="false" type="text">
                            <button type="submit" id="subscribe-button" class="subscribe-button color-bg"><i class="fa fa-rss"></i> Subscribe</button>
                            <label for="subscribe-email" class="subscribe-message"></label>
                        </form>
                    </div>
                    <!-- cs-social -->
                    <div class="cs-social fl-wrap">
                        <ul>
                            <li><a href="#" target="_blank" ><i class="fa fa-facebook-official"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" target="_blank" ><i class="fa fa-chrome"></i></a></li>
                            <li><a href="#" target="_blank" ><i class="fa fa-vk"></i></a></li>
                            <li><a href="#" target="_blank" ><i class="fa fa-whatsapp"></i></a></li>
                        </ul>
                    </div>
                    <!-- cs-social end -->
                </div>
                <!-- container end -->
            </div>
            <!-- cs-wrapper end-->
        </div>
        <!-- Main end -->
        <!--=============== scripts  ===============-->
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/plugins.js"></script>
        <script type="text/javascript" src="js/scripts.js"></script>
    </body>

<!-- Mirrored from citybook.kwst.net/coming-soon.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 Jun 2018 10:15:51 GMT -->
</html>

airbnb/templates/dash.html
<div class="profile-edit-wrap">
    <div class="profile-edit-page-header">
        <h2>Edit profile</h2>
        <div class="breadcrumbs"><a href="#">Home</a><a href="#">Dasboard</a><span>Edit profile</span></div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="fixed-bar fl-wrap">
                <div class="user-profile-menu-wrap fl-wrap">
                    <!-- user-profile-menu-->
                    <div class="user-profile-menu">
                        <h3>Main</h3>
                        <ul>
                          <li><a href="dashboard.html"><i class="fa fa-gears"></i>Dashboard</a></li>													
                            <li><a href="{%url 'accounts:update' request.user.username%}" class="user-profile-act"><i class="fa fa-user-o"></i> Edit profile</a></li>
                            <li><a href="dashboard-messages.html"><i class="fa fa-envelope-o"></i> Messages <span>3</span></a></li>
                            <li><a href="dashboard-password.html"><i class="fa fa-unlock-alt"></i>Change Password</a></li>
                        </ul>
                    </div>
                    <!-- user-profile-menu end-->
                    <!-- user-profile-menu-->
                    <div class="user-profile-menu">
                        <h3>Listings</h3>
                        <ul>
                            <li><a href="{%url 'house:my_lists' %}"><i class="fa fa-th-list"></i> My listigs  </a></li>
                            <li><a href="dashboard-bookings.html"> <i class="fa fa-calendar-check-o"></i> Bookings <span>2</span></a></li>
                            <li><a href="dashboard-review.html"><i class="fa fa-comments-o"></i> Reviews </a></li>
                            <li><a href="{% url 'house:create'%}"><i class="fa fa-plus-square-o"></i> Add New</a></li>
                        </ul>
                    </div>
                    <!-- user-profile-menu end-->                                        
            <a href="{% url 'logout' %}"class="log-out-btn"> Log Out</a>
                </div>
            </div>
        
        </div>
        